url = http://localhost:3000

###
GET  http://localhost:3000

###

GET http://localhost:3000/api

###
POST http://localhost:3000/api
###
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{ 
  "name" :"jeremiah",
  "email": "ezekeiel92@gmail.com",
  "password" : "sfnoer#whoggG"
}

###
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{ 
  "name" :"jeremiah",
  "email": "ejm@gmail.com",
  "password" : "sfnoer#whoggweG"
}

###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{ 
  "email": "ejm@gmail.com",
  "password" : "sfnoer#whoggweG"
}

###
POST http://localhost:3000/api/auth/sign-out